CREATE TABLE PRODUCT(
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    P_NAME VARCHAR(50) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR(50)
);

INSERT INTO PRODUCT VALUES ('nb_ss7', '삼성노트북', 1570000, '시리즈7');
INSERT INTO PRODUCT VALUES ('nb_ama4', '맥북에어', 1200000, 'xcode');
INSERT INTO PRODUCT VALUES ('pc_ibm', 'ibmPC', 750000, 'windows8');

COMMIT;

SELECT * FROM PRODUCT;