--1 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002';

--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) <> 3;

--3
SELECT PROFESSOR_NAME 교수이름
FROM TB_PROFESSOR
WHERE PROFESSOR_SSN LIKE '_______1%'
ORDER BY SUBSTR(PROFESSOR_SSN,1,2) DESC, professor_name ASC;
--ORDER BY PROFESSOR_SSN DESC, professor_name ASC; 이건 내림차순 이상함

--4
SELECT PROFESSOR_NAME 이름
FROM TB_PROJESSOR
WHERE PROFESSOR_NAME LIKE '