--1 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002';

--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) <> 3;

--3
SELECT PROFESSOR_NAME 교수이름
FROM TB_PROFESSOR
WHERE PROFESSOR_SSN LIKE '_______1%'
ORDER BY SUBSTR(PROFESSOR_SSN,1,2) DESC, professor_name ASC;


--4
SELECT SUBSTR(PROFESSOR_NAME,2,2) 이름
FROM TB_PROFESSOR;

--5

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE (TO_NUMBER(SUBSTR(TO_CHAR(TO_DATE(ENTRANCE_DATE,'RR/MM/DD'),'RRRR/MM/DD'),1,4))-TO_NUMBER(LPAD(SUBSTR(STUDENT_SSN,1,2),4,'19')) ) >19;
    
--6    
SELECT TO_CHAR(TO_DATE('2020/12/25','YYYY/MM/DD'),'DAY')
FROM DUAL;

--7
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'), 'YYYY"년"MM"월"DD"일"'), 
        TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'),  'YYYY"년"MM"월"DD"일"'),
        TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'), 'RRRR"년"MM"월"DD"일"'),
        TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'), 'RRRR"년"MM"월"DD"일"')
FROM DUAL;

--8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%'
ORDER BY STUDENT_NO ASC;

--9
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10 -- 답이 다른데 무슨 의도의 문제인지 모르겠음
SELECT DEPARTMENT_NO 학과번호, CAPACITY "학생수(명)"
FROM TB_DEPARTMENT;

--11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12 --으아아 안된다아 GROUP BY 개념 공부해야 할듯
SELECT TERM_NO--DISTINCT SUBSTR(TERM_NO,1,4),
FROM TB_GRADE
GROUP BY TERM_NO--SUBSTR(TERM_NO,1,4)
HAVING STUDENT_NO = 'A112113';

--12
SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) "년도 별 평점" 
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 년도;


--13 --학과별로 0명인 경우도 처리해야함. --COUNT안에 DECODE
SELECT DEPARTMENT_NO 학과코드명, SUM(DECODE(ABSENCE_YN,'Y',1,'N',0)) "휴학생 수"
--, DECODE(ABSENCE_YN,'Y',COUNT(DEPARTMENT_NO),'N',0)--,COUNT(DEPARTMENT_NO)    
FROM TB_STUDENT
--WHERE ABSENCE_YN = 'Y' 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14
SELECT STUDENT_NAME 동일이름, COUNT(*) 동명인수
FROM TB_STUDENT
GROUP BY  STUDENT_NAME
HAVING COUNT(*)>1
ORDER BY STUDENT_NAME;

--15
SELECT NVL(SUBSTR(TERM_NO,1,4),' ') 년도, NVL(SUBSTR(TERM_NO,5,2),' ') 학기, ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),(SUBSTR(TERM_NO,5,2)));
