--1
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;
--2
SELECT DEPARTMENT_NAME ||'의 정원은'|| CAPACITY || '명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;
--3
SELECT STUDENT_NAME
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE s.department_no=d.department_no AND DEPARTMENT_NAME='국어국문학과' AND STUDENT_SSN LIKE '_______2%' AND ABSENCE_YN = 'Y';
--4 --LIKE하면 원하는 값이 안나옴
SELECT STUDENT_NAME, STUDENT_NO
FROM TB_STUDENT
WHERE STUDENT_NO BETWEEN 'A513079' AND 'A513119';
--5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN '20' AND '30';
--6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8
SELECT CLASS_NO
FROM TB_CLASS
WHERE preattending_class_no IS NOT NULL;

--9
SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT;

--10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, ENTRANCE_DATE
FROM TB_STUDENT
WHERE ENTRANCE_DATE LIKE '02%' AND student_address LIKE '전주%' AND ABSENCE_YN = 'N';